# paasta-web-ide-aws 설정 파일 내용
---
name: paasta-web-ide  # 서비스 배포이름(필수)
director_uuid:  8ebe7d77-76d0-4243-88f9-3e775558b3b7 #bosh status 에서 확인한 Director UUID을 입력(필수)

release:
  name: paasta-eclipse-che  #서비스 릴리즈 이름(필수)
  version: 2.0   #서비스 릴리즈 버전(필수):latest 시 업로드된 서비스 릴리즈 최신버전

compilation:
  workers: 4
  network: default
  reuse_compilation_vms: true
  cloud_properties:   # 컴파일 VM을 만드는 데 필요한 IaaS의 특정 속성 (instance_type, availability_zone), 직접 cpu,disk,ram 사이즈를 넣어도 됨
    name: random
    instance_type: m1.xlarge
    availability_zone: nova

# this section describes how updates are handled
update:
  canaries: 1                 # canary 인스턴스 수(필수)
  serial: false
  canary_watch_time: 30000-600000    # canary 인스턴스가 수행하기 위한 대기 시간(필수)
  update_watch_time: 5000-600000    # non-canary 인스턴스가 수행하기 위한 대기 시간(필수)
  max_in_flight: 1            # non-canary 인스턴스가 병렬로 update 하는 최대 개수(필수)

# 네트워크 블록에 나열된 각 서브 블록이 참조 할 수있는 작업이 네트워크 구성을 지정, 네트워크 구성은 네트워크 담당자에게 문의 하여 작성 요망

networks:
- name: default
  subnets:
  - cloud_properties:
      net_id: b7c8c08f-2d3b-4a86-bd10-641cb6faa317
      security_groups:
      - bosh
    dns:
    - 10.244.3.4
    - 8.8.8.8
    gateway: 10.244.2.1
    name: default_unused
    range: 10.244.2.0/24
    reserved:
    - 10.244.2.2 - 10.244.2.69
    static:
    - 10.244.2.70 - 10.244.2.100

- name: public_network    #퍼블릭 네트워크
  type: vip               #openstack 일경우 vip타입만 적어주면 됨
  cloud_properties: {}

resource_pools:               # 배포시 사용하는 resource pools를 명시하며 여러 개의 resource pools 을 사용할 경우 name 은 unique 해야함(필수)
  - name: resource_pools # 고유한 resource pool 이름
    network: default
    stemcell:
      name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent  # stemcell 이름(필수)
      version: 3232.22  # stemcell 버전(필수)
    cloud_properties:         # 컴파일 VM을 만드는 데 필요한 IaaS의 특정 속성을 설명 (instance_type, availability_zone), 직접 cpu, disk, 메모리 설정가능
      instance_type: portal.medium
      availability_zone: nova

jobs:
- name: paasta-web-ide1  #작업 이름(필수)
  template: eclipse-che # job template 이름(필수)
  instances: 1  # job 인스턴스 수(필수)
  resource_pool: resource_pools  # resource_pools block에 정의한 resource pool 이름(필수)
  networks:     # 네트워크 구성정보
  - name: default   # Networks block에서 선언한 network 이름(필수)
    default: [dns, gateway]
    static_ips:
    - 10.244.2.71   # 사용할 IP addresses 정의(필수)
  - name: public_network
    static_ips: 52.78.164.215
  properties:
    che:
      ip: 52.78.164.215
      port: 8080

- name: paasta-web-ide2 #작업 이름(필수)
  template: eclipse-che # job template 이름(필수)
  instances: 1  # job 인스턴스 수(필수)
  resource_pool: resource_pools  # resource_pools block에 정의한 resource pool 이름(필수)
  networks:     # 네트워크 구성정보
  - name: default   # Networks block에서 선언한 network 이름(필수)
    default: [dns, gateway]
    static_ips:
    - 10.244.2.72   # 사용할 IP addresses 정의(필수)
  - name: public_network
    static_ips: 52.78.228.85
  properties:
    che:
      ip: 52.78.228.85
      port: 8080
