# copy of openstack
name: openpaas-glusterfs-service
director_uuid: aafb8d2d-d7e8-4346-a8f2-e746e7b21b87 

releases:
- name: openpaas-glusterfs
  version: 1.0

update:
  canaries: 1
  canary_watch_time: 30000-600000
  max_in_flight: 1
  update_watch_time: 30000-600000

compilation:
  cloud_properties:
    instance_type: m1.medium
  network: openpaas_network
  reuse_compilation_vms: true
  workers: 2

jobs:
- instances: 1
  name: mysql
  networks:
  - name: openpaas_network
    static_ips: 10.0.0.70
  persistent_disk: 10000
  properties:
    admin_username: root 
    admin_password: admin 
  release: openpaas-glusterfs
  resource_pool: services-small
  template: mysql

- instances: 1
  name: openpaas-glusterfs-java-broker
  networks:
  - name: openpaas_network
    static_ips: 10.0.0.71 
  properties:
    jdbc_ip: 10.0.0.70 
    jdbc_pwd: admin
    jdbc_port: 3306
    log_dir: openpaas-glusterfs-java-broker
    log_file: openpaas-glusterfs-java-broker
    log_level: INFO
    glusterfs_url: 54.199.136.22
    glusterfs_tenantname: service
    glusterfs_username: swift
    glusterfs_password: password
  release: openpaas-glusterfs
  resource_pool: services-small
  template: op-glusterfs-java-broker

- instances: 1
  lifecycle: errand
  name: broker-registrar
  networks:
  - name: openpaas_network
  properties:
    broker:
      host: 10.0.0.71 
      name: Glusterfs
      password: cloudfoundry 
      username: admin 
      protocol: http
      port: 8080
    cf:
      api_url: https://api.controller.open-paas.com 
      admin_username: admin 
      admin_password: admin 
  release: openpaas-glusterfs
  resource_pool: services-small
  template: broker-registrar

- instances: 1
  lifecycle: errand
  name: broker-deregistrar
  networks:
  - name: openpaas_network
  properties:
    cf:
      api_url: https://api.controller.open-paas.com 
      admin_username: admin 
      admin_password: admin 
  release: openpaas-glusterfs
  resource_pool: services-small
  template: broker-deregistrar

networks:
- name: openpaas_network
  subnets:
  - cloud_properties:
      subnet: subnet-e300eabb
      security_groups:
      - cf-security
      - bosh-security
    dns:
    - 10.0.0.6
    - 8.8.8.8 
    gateway: 10.0.0.1 
    range: 10.0.0.0/24 
    reserved:
    - 10.0.0.2 - 10.0.0.69 
    static:
    - 10.0.0.70
    - 10.0.0.71
  type: manual


properties: {}

resource_pools:
- cloud_properties:
    instance_type: m1.small
  name: services-small
  network: openpaas_network
  stemcell:
    name: bosh-aws-xen-ubuntu-trusty-go_agent
    version: "3147"
