name: openpaas-glusterfs-service
director_uuid: 46965538-fe7f-4260-b5df-ef9411558b99

releases:
- name: openpaas-glusterfs
  version: 1.0

update:
  canaries: 1
  canary_watch_time: 30000-600000
  max_in_flight: 1
  update_watch_time: 30000-600000

compilation:
  cloud_properties:
    name: random
    #cpu: 4
    #disk: 20480
    #ram: 4096
  network: openpaas_network
  reuse_compilation_vms: true
  workers: 4 

disk_pools:
- cloud_properties: {}
  disk_size: 10000
  name: mysql-persistent-disk

jobs:
- instances: 1
  name: mysql
  networks:
  - name: openpaas_network
    static_ips: 10.244.20.2
  persistent_disk_pool: mysql-persistent-disk
  properties:
    admin_username: root
    admin_password: admin
  release: openpaas-glusterfs
  resource_pool: services-small
  template: mysql

- instances: 1
  name: openpaas-glusterfs-java-broker
  networks:
  - name: openpaas_network
    static_ips: 10.244.20.3
  properties:
    jdbc_ip: 10.244.20.2
    jdbc_pwd: admin
    jdbc_port: 3306
    log_dir: openpaas-glusterfs-java-broker
    log_file: openpaas-glusterfs--java-broker
    log_level: INFO
    glusterfs_url: 54.199.136.22
    glusterfs_tenantname: service
    glusterfs_username: swift
    glusterfs_password: password
  release: openpaas-glusterfs
  resource_pool: services-small
  template: op-glusterfs-java-broker

- instances: 1
  lifecycle: errand
  name: broker-registrar
  networks:
  - name: openpaas_network
  properties:
    broker:
      host: 10.244.20.3
      name: glusterfs-service
      password: cloudfoundry
      username: admin
      protocol: http
      port: 8080
    cf:
      admin_password: admin
      admin_username: admin
      api_url: https://api.bosh-lite.com
      skip_ssl_validation: true
  release: openpaas-glusterfs
  resource_pool: services-small
  template: broker-registrar

- instances: 1
  lifecycle: errand
  name: broker-deregistrar
  networks:
  - name: openpaas_network
  properties:
    broker:
      name: glusterfs-service
    cf:
      admin_password: admin
      admin_username: admin
      api_url: https://api.bosh-lite.com
      skip_ssl_validation: true
  release: openpaas-glusterfs
  resource_pool: services-small
  template: broker-deregistrar

networks: 
- name: openpaas_network
  subnets:
  - cloud_properties:
      name: random
    #dns:
    #- 10.30.20.24
    #- 8.8.8.8
    #gateway: 10.30.20.23
    #name: default_unused
    range: 10.244.20.0/24
    reserved:
    - 10.244.20.1
    static:
    - 10.244.20.2 - 10.244.20.3
  type: manual

properties: {}

resource_pools:
- cloud_properties:
    name: random
    #cpu: 2
    #disk: 10480
    #ram: 4096
  name: services-small
  #size: 5
  network: openpaas_network
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: "389"
