---
dev_name: openpass-paasta-pinpoint-release
latest_release_filename: /home/inception/bosh-space/release/openpass-paasta-pinpoint-release/dev_releases/openpass-paasta-pinpoint-release/openpass-paasta-pinpoint-release-0+dev.1.yml
