<% num_collectors = 2 %>
<% num_slaves = 2 %>
<% num_webui = 2 %>
<% h_master_ip = '10.30.70.71' %>
<% h_secondary_ip = '10.30.70.72' %>
#<% h_slave_ips = ["10.30.70.73", "10.30.70.74", "10.30.70.75"] %>
<% h_slave_ips = ["10.30.70.73", "10.30.70.74"] %>
#<% collector_ips = ["10.30.70.40","10.30.70.41","10.30.70.43"] %>
<% collector_ips = ["10.30.70.40","10.30.70.41"] %>
<% haproxy_webui_ip = '10.30.70.78' %>
<% haproxy_webui_public_ip = '115.68.46.182' %>
<% haproxy_webui_http_port = '80' %>
#<% webui_ips = ["10.30.70.79", "10.30.70.80", "10.30.70.81"] %>
<% webui_ips = ["10.30.70.79", "10.30.70.80"] %>
<% broker_ip = '10.30.70.82' %>
<% tcp_listen_port = '29994' %>
<% udp_stat_listen_port = '29995' %>
<% udp_span_listen_port = '29996' %>
---
name: openpaas-paasta-pinpoint
director_uuid: 0bc8d3c2-e032-4c7e-a99c-e23eea7091fc 
release:
  name: openpaas-paasta-pinpoint-release
  version: latest
compilation:
  workers: 6
  network: default
  cloud_properties:
    ram: 4096
    disk: 8096
    cpu: 4
update:
  canaries: 1
  canary_watch_time: 120000
  update_watch_time: 120000
  max_in_flight: 8

networks:
- name: default
  subnets:
  - cloud_properties:
      name: Internal
    dns:
    - 10.30.20.24
    - 8.8.8.8
    gateway: 10.30.20.23
    name: default_unused
    range: 10.30.0.0/16
    reserved:
    - 10.30.20.0 - 10.30.20.22
    - 10.30.20.24 - 10.30.20.255
    - 10.30.40.0 - 10.30.40.255
    - 10.30.60.0 - 10.30.60.112
    static:
    - 10.30.70.0 - 10.30.70.255 
- name: public_network
  type: manual
  subnets:
  - cloud_properties:
      name: External
    dns:
    - 8.8.8.8
    range: 115.68.46.176/28
    gateway: 115.68.46.177
    static:
    - <%= haproxy_webui_public_ip %>

resource_pools:
  - name: pinpoint_small 
    network: default
    stemcell:
      name: bosh-vsphere-esxi-ubuntu-trusty-go_agent
      version: 3215.4 
    cloud_properties:
      cpu: 1
      disk: 4096
      ram: 1024
  - name: pinpoint_medium
    network: default
    stemcell:
      name: bosh-vsphere-esxi-ubuntu-trusty-go_agent
      version: 3215.4
    cloud_properties:
      cpu: 2
      disk: 8192
      ram: 2048
jobs:
- name: h_slave
  template: h_slave
  instances: <%= num_slaves %>
  resource_pool: pinpoint_small
  networks:
  - name: default
    static_ips:
    <% h_slave_ips.each do |ip| %>
    - <%= ip %>
    <% end %>
- name: h_secondary
  template: h_secondary
  instances: 1
  resource_pool: pinpoint_small
  networks:
  - name: default
    static_ips:
    - <%= h_secondary_ip %>
- name: h_master
  template: h_master
  instances: 1
  resource_pool: pinpoint_medium
  networks:
  - name: default
    static_ips:
    - <%= h_master_ip %>
- name : h_master_register
  template : h_master_register
  instances: 1
  lifecycle: errand   
  resource_pool: pinpoint_small
  networks:
  - name: default 
- name: collector
  template: collector
  instances: <%= num_collectors %>
  resource_pool: pinpoint_medium
  networks:
  - name: default
    static_ips:
    <% collector_ips.each do |ip| %>
    - <%= ip %>
    <% end %>
- name: haproxy_webui
  template: haproxy_webui
  instances: 1
  resource_pool: pinpoint_small
  networks:
  - name: default
    static_ips:
    - <%= haproxy_webui_ip %>
  - name: public_network
    default: [dns, gateway]
    static_ips: <%= haproxy_webui_public_ip %>
- name: webui
  template: webui
  instances: <%= num_webui %>
  resource_pool: pinpoint_small
  networks:
  - name: default
    static_ips:
    <% webui_ips.each do |ip| %>
    - <%= ip %>
    <% end %>
- name: pinpoint_broker
  template: broker
  instances: 1
  resource_pool: pinpoint_small
  networks:
  - name: default
    static_ips:
    - <%= broker_ip %>

properties:
  master:
    host_name: h-master
    host_ip: <%= h_master_ip %>
    port: 9000
    http_port: 50070
    replication: <%= num_slaves %>
    tcp_listen_port: <%= tcp_listen_port %>
    udp_stat_listen_port: <%= udp_stat_listen_port %>
    udp_span_listen_port: <%= udp_span_listen_port %>
  broker:
    collector_ips: <%= collector_ips %>
    collector_tcp_port: <%= tcp_listen_port %>
    collector_stat_port: <%= udp_stat_listen_port %>
    collector_span_port: <%= udp_span_listen_port %>
    dashboard_uri: http://<%= haproxy_webui_public_ip %>:<%= haproxy_webui_http_port %>/#/main
  secondary:
    host_name: h-secondary
    host_ip: <%= h_secondary_ip %>
    http_port: 50090
  yarn:
    host_name: h-master
    host_ip: <%= h_master_ip %>
    resource_tracker_port: 8025
    scheduler_port: 8030
    resourcemanager_port: 8040
  slave:
    host_names:
      <% num_slaves.times do |i| %>
      <%= "- h-slave#{i}" %>
      <% end %>
    host_ips: 
      <% h_slave_ips.each do |ip| %>
      - <%= ip %>
      <% end %>
  collector:
    host_names:
      <% num_collectors.times do |i| %>
      <%= "- h-collector#{i}" %>
      <% end %>
    host_ips: 
      <% collector_ips.each do |ip| %>
      - <%= ip %>
      <% end %>
  haproxy:
    host_name: haproxy-webui
    host_ip: <%= haproxy_webui_ip %>
    http_port: <%= haproxy_webui_http_port %>
  webui:
    host_names:
      <% num_webui.times do |i| %>
      <%= "- h-webui#{i}" %>
      <% end %>
    host_ips: 
      <% webui_ips.each do |ip| %>
      - <%= ip %>
      <% end %>
