---
name: openpaas-paasta-pinpoint  # 서비스 배포이름(필수) bosh deployments 로 확인가능한 이름
director_uuid: 7d8250a8-459a-40be-8c3a-e6ac95aa91ce # Director UUID을 입력(필수) bosh status 명령으로 확인가능

release:
  name: openpaas-paasta-pinpoint-release  #서비스 릴리즈 이름(필수) bosh releases로 확인가능
  version: latest   #서비스 릴리즈 버전(필수):latest 시 업로드된 서비스 릴리즈 최신버전

compilation:          # 컴파일시 필요한 가상머신의 속성(필수)
  workers: 2          # 컴파일 하는 가상머신의 최대수(필수)
  network: default    # Networks block에서 선언한 network 이름(필수)
  reuse_compilation_vms: true
  cloud_properties:   # 컴파일 VM을 만드는 데 필요한 IaaS의 특정 속성 (instance_type, availability_zone), 직접 cpu,disk,ram 사이즈를 넣어도 됨
    instance_type: t2.medium

# this section describes how updates are handled
update:
  canaries: 1                 # canary 인스턴스 수(필수)
  canary_watch_time: 120000    # canary 인스턴스가 수행하기 위한 대기 시간(필수)
  update_watch_time: 120000    # non-canary 인스턴스가 수행하기 위한 대기 시간(필수)
  max_in_flight: 4            # non-canary 인스턴스가 병렬로 update 하는 최대 개수(필수)

networks:                     # 네트워크 블록에 나열된 각 서브 블록이 참조 할 수있는 작업이 네트워크 구성을 지정, 네트워크 구성은 네트워크 담당자에게 문의 하여 작성 요망
- name: default
  subnets:
  - cloud_properties:
      subnet: subnet-d5af89a3
      security_groups:
      - pcf-stack-OpsManStack-HLX51TTHO61P-PcfOpsManagerSecurityGroup-1RKIZCNBZQK3Q
      - pcf-stack-OpsManStack-HLX51TTHO61P-PcfVmsSecurityGroup-S7ESFV1N2AXI
    dns:                      # DNS 정보
    - 10.0.0.2
    gateway: 10.0.0.1
    range: 10.0.0.0/16
    reserved:                 # 설치시 제외할 IP 설정
    - 10.0.0.2-10.0.0.52
    static:
    - 10.0.0.61 - 10.0.0.69 #사용 가능한 IP 설정

- name: public_network    #퍼블릭 네트워크
  type: vip
  cloud_properties: {}

resource_pools:               # 배포시 사용하는 resource pools를 명시하며 여러 개의 resource pools 을 사용할 경우 name 은 unique 해야함(필수)
  - name: small # 고유한 resource pool 이름
    network: default
    stemcell:
      name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent  # stemcell 이름(필수)
      version: 3146.11 # stemcell 버전(필수)
    cloud_properties:         # 컴파일 VM을 만드는 데 필요한 IaaS의 특정 속성을 설명 (instance_type, availability_zone), 직접 cpu, disk, 메모리 설정가능
      instance_type: t2.small
  - name: medium  # 고유한 resource pool 이름
    network: default
    stemcell:
      name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent  # stemcell 이름(필수)
      version: 3146.11 # stemcell 버전(필수)
    cloud_properties:         # 컴파일 VM을 만드는 데 필요한 IaaS의 특정 속성을 설명 (instance_type, availability_zone), 직접 cpu, disk, 메모리 설정가능
      instance_type: t2.medium
jobs:
- name: hbase
  template: hbase
  instances: 1
  resource_pool: medium  # resource_pools block에 정의한 resource pool 이름(필수)
  # persistent_disk: 4096  # 영구적 디스크 사이즈 정의(옵션): 16G
  networks:     # 네트워크 구성정보
  - name: default   # Networks block에서 선언한 network 이름(필수) 내부 네트워크 설정
    static_ips:
    - 10.0.0.61   # 사용할 내부 IP addresses 정의(필수) 

- name: collector
  template: collector
  instances: 1
  resource_pool: medium  # resource_pools block에 정의한 resource pool 이름(필수)
  # persistent_disk: 4096  # 영구적 디스크 사이즈 정의(옵션): 16G
  networks:     # 네트워크 구성정보
  - name: default   # Networks block에서 선언한 network 이름(필수) 내부 네트워크 설정
    static_ips:
    - 10.0.0.65   # 사용할 내부 IP addresses 정의(필수) 
    
- name: webui
  template: webui
  instances: 1
  resource_pool: small  # resource_pools block에 정의한 resource pool 이름(필수)
  # persistent_disk: 4096  # 영구적 디스크 사이즈 정의(옵션): 16G
  networks:     # 네트워크 구성정보
  - name: default   # Networks block에서 선언한 network 이름(필수) 내부 네트워크 설정
    default: [dns,gateway]
    static_ips:
    - 10.0.0.68   # 사용할 내부 IP addresses 정의(필수) 
  - name: public_network    # Public network 설정
    static_ips: 50.17.162.106 # change it

- name: pinpoint-broker
  template: broker
  instances: 1
  resource_pool: small  # resource_pools block에 정의한 resource pool 이름(필수)
  # persistent_disk: 4096  # 영구적 디스크 사이즈 정의(옵션): 16G
  networks:     # 네트워크 구성정보
  - name: default   # Networks block에서 선언한 network 이름(필수) 내부 네트워크 설정
    static_ips:
    - 10.0.0.67   # 사용할 내부 IP addresses 정의(필수) 

properties:
  hbase:
    host_ip: 10.0.0.61
    host_name: hbase-test-host-name
    tcp_listen_port: 29994
    udp_stat_listen_port: 29995
    udp_span_listen_port: 29996
  broker:
    collector_ips: ["10.0.0.65","10.0.0.66","10.0.0.67"] 
    collector_span_port: 29996
    collector_stat_port: 29995
    collector_tcp_port: 29994
    dashboard_uri: http://50.17.162.106:8080/#/main
