---
name: openpaas-paasta-pinpoint  # 서비스 배포이름(필수) bosh deployments 로 확인가능한 이름
director_uuid: 0bc8d3c2-e032-4c7e-a99c-e23eea7091fc # Director UUID을 입력(필수) bosh status 명령으로 확인가능

release:
  name: openpaas-paasta-pinpoint-release  #서비스 릴리즈 이름(필수) bosh releases로 확인가능
  version: latest   #서비스 릴리즈 버전(필수):latest 시 업로드된 서비스 릴리즈 최신버전

compilation:          # 컴파일시 필요한 가상머신의 속성(필수)
  workers: 2          # 컴파일 하는 가상머신의 최대수(필수)
  network: default    # Networks block에서 선언한 network 이름(필수)
  cloud_properties:   # 컴파일 VM을 만드는 데 필요한 IaaS의 특정 속성 (instance_type, availability_zone), 직접 cpu,disk,ram 사이즈를 넣어도 됨
    ram: 2048
    disk: 8096
    cpu: 2

# this section describes how updates are handled
update:
  canaries: 1                 # canary 인스턴스 수(필수)
  canary_watch_time: 120000    # canary 인스턴스가 수행하기 위한 대기 시간(필수)
  update_watch_time: 120000    # non-canary 인스턴스가 수행하기 위한 대기 시간(필수)
  max_in_flight: 4            # non-canary 인스턴스가 병렬로 update 하는 최대 개수(필수)

networks:                     # 네트워크 블록에 나열된 각 서브 블록이 참조 할 수있는 작업이 네트워크 구성을 지정, 네트워크 구성은 네트워크 담당자에게 문의 하여 작성 요망
- name: default
  subnets:
  - cloud_properties:
      name: Internal          # vsphere 에서 사용하는 network 이름(필수)
    dns:                      # DNS 정보
    - 10.30.20.24
    - 8.8.8.8
    gateway: 10.30.20.23
    name: default_unused
    range: 10.30.0.0/16
    reserved:                 # 설치시 제외할 IP 설정
    - 10.30.20.0 - 10.30.20.22
    - 10.30.20.24 - 10.30.20.255
    - 10.30.40.0 - 10.30.40.255
    - 10.30.60.0 - 10.30.60.112
    static:
    - 10.30.70.0 - 10.30.70.255 #사용 가능한 IP 설정

- name: public_network    #퍼블릭 네트워크
  type: manual
  subnets:
  - cloud_properties:
      name: External
    dns:
    - 8.8.8.8
    gateway: 115.68.46.177
    range: 115.68.46.176/28
    static:
    - 115.68.46.181

resource_pools:               # 배포시 사용하는 resource pools를 명시하며 여러 개의 resource pools 을 사용할 경우 name 은 unique 해야함(필수)
  - name: resource_pools # 고유한 resource pool 이름
    network: default
    stemcell:
      name: bosh-vsphere-esxi-ubuntu-trusty-go_agent  # stemcell 이름(필수)
      version: 3147 # stemcell 버전(필수)
    cloud_properties:         # 컴파일 VM을 만드는 데 필요한 IaaS의 특정 속성을 설명 (instance_type, availability_zone), 직접 cpu, disk, 메모리 설정가능
      cpu: 1
      disk: 8192
      ram: 2048
jobs:
- name: hbase
  template: hbase
  instances: 1
  resource_pool: resource_pools  # resource_pools block에 정의한 resource pool 이름(필수)
  # persistent_disk: 4096  # 영구적 디스크 사이즈 정의(옵션): 16G
  networks:     # 네트워크 구성정보
  - name: default   # Networks block에서 선언한 network 이름(필수) 내부 네트워크 설정
    static_ips:
    - 10.30.70.30   # 사용할 내부 IP addresses 정의(필수) 

- name: collector
  template: collector
  instances: 1
  resource_pool: resource_pools  # resource_pools block에 정의한 resource pool 이름(필수)
  # persistent_disk: 4096  # 영구적 디스크 사이즈 정의(옵션): 16G
  networks:     # 네트워크 구성정보
  - name: default   # Networks block에서 선언한 network 이름(필수) 내부 네트워크 설정
    static_ips:
    - 10.30.70.40   # 사용할 내부 IP addresses 정의(필수) 
    
- name: webui
  template: webui
  instances: 1
  resource_pool: resource_pools  # resource_pools block에 정의한 resource pool 이름(필수)
  # persistent_disk: 4096  # 영구적 디스크 사이즈 정의(옵션): 16G
  networks:     # 네트워크 구성정보
  - name: default   # Networks block에서 선언한 network 이름(필수) 내부 네트워크 설정
    static_ips:
    - 10.30.70.50   # 사용할 내부 IP addresses 정의(필수) 
  - name: public_network    # Public network 설정
    default: [dns, gateway]  
    static_ips: 115.68.46.181  # change it!    

- name: pinpoint-broker
  template: broker
  instances: 1
  resource_pool: resource_pools  # resource_pools block에 정의한 resource pool 이름(필수)
  # persistent_disk: 4096  # 영구적 디스크 사이즈 정의(옵션): 16G
  networks:     # 네트워크 구성정보
  - name: default   # Networks block에서 선언한 network 이름(필수) 내부 네트워크 설정
    static_ips:
    - 10.30.70.51   # 사용할 내부 IP addresses 정의(필수) 

properties:
  hbase:
    host_ip: 10.30.70.30
    host_name: hbase-test-host-name
    tcp_listen_port: 29994
    udp_stat_listen_port: 29995
    udp_span_listen_port: 29996
  broker:
    collector_ips: ["10.30.70.40","10.30.70.41","10.30.70.43"]
    collector_span_port: 29996
    collector_stat_port: 29995
    collector_tcp_port: 29994
    dashboard_uri: http://115.68.46.181:8080/#/main
