---
dev_name: apiplatform_vsphere
latest_release_filename: /mnt/kimdojun/bosh/openpaas-service-release/open-apiplatform-release/releases/oepnpaas-apiplatform-release/oepnpaas-apiplatform-release-1.yml
