---
name: paasta-apiplatform-service                     # 서비스 배포이름(필수)

director_uuid: b63ac41b-8215-4926-bb43-5dcc982eff6a  # bosh status 에서 확인한 Director UUID을 입력(필수)

releases:
- {name: paasta-apiplatform, version: 2.0}  # 서비스 릴리즈 이름(필수), 서비스 릴리즈 버전(필수): latest 시 업로드 된 서비스 릴리즈 최신버전

update:
  canaries: 1                          # canary 인스턴스 수(필수)
  canary_watch_time: 30000-600000      # canary 인스턴스가 수행하기 위한 대기 시간(필수)
  max_in_flight: 1                     # non-canary 인스턴스가 병렬로 update 하는 최대 개수(필수)
  update_watch_time: 30000-600000      # 컴파일 시 필요한 가상머신의 속성(필수)

networks:                           # 네트워크 블록에 나열된 각 서브 블록이 참조 할 수있는 작업이 네트워크 구성을 지정, 네트워크 구성은 네트워크 담당자에게 문의 하여 작성 요망
- name: selfservice
  subnets:
  - cloud_properties:
      net_id: b7c8c08f-2d3b-4a86-bd10-641cb6faa317
      security_groups:
        - bosh
    dns:
      - 10.244.3.4
    gateway: 10.244.2.1
    range: 10.244.2.0/24
    reserved: 
    - 10.244.2.2 - 10.244.2.199
    static:
    - 10.244.2.200 - 10.244.2.210
  type: manual

resource_pools:                                     # 배포시 사용하는 resource pools를 명시하며 여러 개의 resource pools 을 사용할 경우 name은 고유해야함(필수)
- cloud_properties:
    instance_type: portal.small
    availability_zone: nova
  name: services-small                              # 고유한 resource pool 이름
  env:
    bosh:
      password: "$6$4gDD3aV0rdqlrKC$2axHCxGKIObs6tAmMTqYCspcdvQXh3JJcvWOY2WGb4SrdXtnCyNaWlrf3WEqvYR2MYizEGp3kMmbpwBC6jsHt0"
  network: selfservice
  stemcell:
    name: bosh-openstack-kvm-ubuntu-trusty-go_agent   # stemcell 이름(필수)
    version: 3309                                    # stemcell 버전(필수)
 - cloud_properties:
    instance_type: portal.medium
    availability_zone: nova
  name: services-medium                              # 고유한 resource pool 이름
  env:
    bosh:
      password: "$6$4gDD3aV0rdqlrKC$2axHCxGKIObs6tAmMTqYCspcdvQXh3JJcvWOY2WGb4SrdXtnCyNaWlrf3WEqvYR2MYizEGp3kMmbpwBC6jsHt0"
  network: selfservice
  stemcell:
    name: bosh-openstack-kvm-ubuntu-trusty-go_agent   # stemcell 이름(필수)
    version: 3309                                    # stemcell 버전(필수)

compilation:                     # 컴파일 VM을 만드는 데 필요한 IaaS의 특정 속성 (instance_type, availability_zone), 직접 cpu,disk,ram 사이즈를 넣어도 됨
    name: random                 
    instance_type: portal.medium  
    availability_zone: nova
  network: selfservice
  reuse_compilation_vms: true    # 컴파일 시 VM 재사용 여부(옵션)
  workers: 1                     # 컴파일 하는 가상머신의 최대수(필수)

jobs:
- name: mariadb                               # 작업 이름(필수): DB 서버
  instances: 1                                # job 인스턴스 수(필수)
  template: selfservice                       # job template 이름(필수) 
  resource_pool: services-medium               # Resource Pools block에 정의한 resource pool 이름(필수)
  networks:                                   # 네트워크 구성정보
  - name: default                             # Networks block에서 선언한 network 이름
    static_ips: 10.244.2.210                  # 사용할 IP addresses 정의(필수): db서버
  properties:                                 # job에 대한 속성을 지정(필수)
    admin_username: root                      # DB 어드민 유저이름 
    admin_password: openpaas                  # DB 어드민 패스워드
    apiplatform_username: wso2                # API Platform(API Manager)의 DB 접속 유저이름
    apiplatform_password: openpaas            # API Platform(API Manager)의 DB 접속 패스워드
    apiplatform_broker_username: apiplatform  # API Platform Service Broker의 DB 접속 유저이름
    apiplatform_broker_password: openpaas     # API Platform Service Broker의 DB 접속 패스워드

- name: bam                            # 작업 이름(필수): BAM
  instances: 1                         # job 인스턴스 수(필수)
  template: bam                        # job template 이름(필수)
  resource_pool: services-small       # Resource Pools block에 정의한 resource pool 이름(필수)
  networks:                            # 네트워크 구성정보
  - name: selfservice                  # Networks block에서 선언한 network 이름
    static_ips: 10.244.2.203           # 사용할 IP addresses 정의(필수): BAM

- name: apimanager                    # 작업 이름(필수): API Platform(API Manager)
  instances: 1                        # job 인스턴스 수(필수)
  template: apimanager                # job template 이름(필수)
  resource_pool: services-small      # Resource Pools block에 정의한 resource pool 이름(필수)
  networks:                           # 네트워크 구성정보
  - name: selfservice                 # Networks block에서 선언한 network 이름
    static_ips: 10.244.2.201          # 사용할 IP addresses 정의(필수): API Platform(API Manager)

- name: apiplatform-broker            # 작업 이름(필수): API Platform Service Broker
  instances: 1                        # job 인스턴스 수(필수)
  template: apiplatform-broker        # job template 이름(필수)
  resource_pool: services-small       # Resource Pools block에 정의한 resource pool 이름(필수)
  networks:                           # 네트워크 구성정보
  - name: selfservice                 # Networks block에서 선언한 network 이름
    static_ips: 10.244.2.200          # 사용할 IP addresses 정의(필수): API Platform Service Broker
 
  properties:                                  # job에 대한 속성을 지정(필수)
    catalog_login_id: admin                    # 카탈로그 API를 사용하기 위한 API플랫폼 유저 아이디
    catalog_login_password: admin              # 카탈로그 API를 사용하기 위한 API플랫폼 유저 패스워드
    apimanager_url: http://10.244.2.201        # API Platform(API Manager) URL
    database_ip: 10.244.2.210                  # DB 접속 URL
    apiplatform_broker_username: apiplatform   # API Platform Service Broker의 DB 접속 유저이름
    apiplatform_broker_password: openpaas      # API Platform Service Broker의 DB 접속 패스워드

- name: broker-registrar                        # 작업 이름(필수): 서비스 브로커 등록
  template: broker-registrar                    # job template 이름(필수)
  instances: 1                                  # job 인스턴스 수(필수)
  lifecycle: errand                             # bosh deploy시 vm에 생성되어 설치 되지 않고 bosh errand 로 실행할 때 설정, 주로 테스트 용도에 쓰임
  resource_pool: services-small                 # Resource Pools block에 정의한 resource pool 이름(필수)
  networks:                                     # 네트워크 구성정보
  - name: selfservice                           # Networks block에서 선언한 network 이름
  properties:                                   # job에 대한 속성을 지정(필수)
    cf:                                         # PaaS-TA 접속 정보
      api_url: http://api.115.68.46.186.xip.io  # PaaS-TA 접속 URL
      admin_username: "admin"                   # PaaS-TA 접속 유저이름
      admin_password: "admin"                   # PaaS-TA 접속 패스워드
      skip_ssl_validation: "true"               # PaaS-TA 접속 옵션의 일부
    broker:                                     # API Platform Service Broker 설정정보
      protocol: http                            # API Platform Service Broker 접속 프로토콜
      host: 10.244.2.200                        # API Platform Service Broker 접속 URL
      port: 8080                                # API Platform Service Broker 접속 포트
      name: apiplatform-serivce-broker          # API Platform Service Broker 생성명
      username: "admin"                         # API Platform Service Broker auth 유저이름
      password: "cloudfoundry"                  # API Platform Service Broker auth 패스워드

- name: broker-deregistrar                     # 작업 이름(필수): 서비스 브로커 삭제
  template: broker-deregistrar                 # job template 이름(필수)
  instances: 1                                 # job 인스턴스 수(필수)
  lifecycle: errand                            # bosh deploy시 vm에 생성되어 설치 되지 않고 bosh errand 로 실행할 때 설정, 주로 테스트 용도에 쓰임
  resource_pool: services-small                # Resource Pools block에 정의한 resource pool 이름(필수)
  networks:                                    # 네트워크 구성정보
  - name: selfservice                          # Networks block에서 선언한 network 이름
  properties:                                  # job에 대한 속성을 지정(필수)
    cf:                                        # PaaS-TA 접속 정보    
      api_url: http://api.115.68.46.186.xip.io # PaaS-TA 접속 URL
      admin_username: "admin"                  # PaaS-TA 접속 유저이름
      admin_password: "admin"                  # PaaS-TA 접속 패스워드
      skip_ssl_validation: "true"              # PaaS-TA 접속 옵션의 일부
    broker:                                    # API Platform Service Broker 설정정보
      name: apiplatform-service-broker         # API Platform Service Broker 생성명