name: op-mysql-dev-service
director_uuid: 6e0f7c41-2415-4319-98aa-38109597aff4

releases:
- name: op-mysql-dev
  version: latest

update:
  canaries: 1
  canary_watch_time: 30000-600000
  max_in_flight: 1
  update_watch_time: 30000-600000

compilation:
  cloud_properties:
    cpu: 4
    disk: 20480
    ram: 4096
  network: op_dev_network
  reuse_compilation_vms: true
  workers: 3

jobs:
- instances: 1
  name: mysql_z1
  networks:
  - name: op_dev_network
    static_ips: 10.30.40.191
  persistent_disk: 10000
  properties:
    admin_password: c1oudc0w
    cluster_ips:
    - 10.30.40.191
    - 10.30.40.192
    - 10.30.40.193
    network_name: op_dev_network
    seeded_databases: null
    syslog_aggregator: null
    collation_server: utf8_unicode_ci
    character_set_server: utf8
  release: op-mysql-dev
  resource_pool: services-small
  template: mysql

- instances: 1
  name: mysql_z2
  networks:
  - name: op_dev_network
    static_ips: 10.30.40.192
  persistent_disk: 10000
  properties:
    admin_password: c1oudc0w
    cluster_ips:
    - 10.30.40.191
    - 10.30.40.192
    - 10.30.40.193
    network_name: op_dev_network
    seeded_databases: null
    syslog_aggregator: null
    collation_server: utf8_unicode_ci
    character_set_server: utf8
  release: op-mysql-dev
  resource_pool: services-small
  template: mysql

- instances: 1
  name: mysql_z3
  networks:
  - name: op_dev_network
    static_ips: 10.30.40.193
  persistent_disk: 10000
  properties:
    admin_password: c1oudc0w
    cluster_ips:
    - 10.30.40.191
    - 10.30.40.192
    - 10.30.40.193
    network_name: op_dev_network
    seeded_databases: null
    syslog_aggregator: null
    collation_server: utf8_unicode_ci
    character_set_server: utf8
  release: op-mysql-dev
  resource_pool: services-small
  template: mysql

- instances: 1
  name: proxy
  networks:
  - name: op_dev_network
    static_ips: 10.30.40.194
  properties:
    cluster_ips:
    - 10.30.40.191
    - 10.30.40.192
    - 10.30.40.193
    external_host: cf.open-paas.com
    nats:
      machines:
      - 10.30.40.11
      password: eaa139af583c
      port: 4222
      user: nats
    network_name: op_dev_network
    proxy:
      api_password: eaa139af583c
      api_username: api
      api_force_https: false
    syslog_aggregator: null
  release: op-mysql-dev
  resource_pool: services-small
  template: proxy

- instances: 1
  name: op-mysql-java-broker
  networks:
  - name: op_dev_network
    static_ips: 10.30.40.195
  properties:
    jdbc_ip: 10.30.40.194
    jdbc_pwd: c1oudc0w
    jdbc_port: 3306
    log_dir: op-mysql-java-broker
    log_file: op-mysql-java-broker
    log_level: INFO
  release: op-mysql-dev
  resource_pool: services-small
  template: op-mysql-java-broker

- instances: 1
  lifecycle: errand
  name: broker-registrar
  networks:
  - name: op_dev_network
  properties:
    broker:
      host: 10.30.40.195
      name: Mysql-DB
      password: cloudfoundry
      username: admin
      protocol: http
      port: 8080
    cf:
      admin_password: eaa139af583c
      admin_username: admin
      api_url: http://api.cf.open-paas.com
  release: op-mysql-dev
  resource_pool: services-small
  template: broker-registrar

- instances: 1
  lifecycle: errand
  name: broker-deregistrar
  networks:
  - name: op_dev_network
  properties:
    broker:
      host: 10.30.40.195
      name: Mysql-DB
      password: cloudfoundry
      username: admin
      protocol: http
      port: 8080
    cf:
      admin_password: eaa139af583c
      admin_username: admin
      api_url: http://api.cf.open-paas.com
  release: op-mysql-dev
  resource_pool: services-small
  template: broker-deregistrar

meta:
  apps_domain: cf.open-paas.com
  environment: null
  external_domain: cf.open-paas.com
  nats:
    machines:
    - 10.30.40.11
    password: eaa139af583c
    port: 4222
    user: nats
  syslog_aggregator: null

networks:
- name: op_dev_network
  subnets:
  - cloud_properties:
      name: Internal
    dns:
    - 10.30.20.24
    - 8.8.8.8
    gateway: 10.30.20.23
    name: default_unused
    range: 10.30.0.0/16
    reserved:
    - 10.30.0.1 - 10.30.0.5
    #- 10.30.0.1 - 10.30.10.254
    #- 10.30.40.1 - 10.30.40.100
    #- 10.30.40.201 - 10.30.254.254
    static:
    - 10.30.40.110 - 10.30.40.200
  type: manual
properties: {}
resource_pools:
- cloud_properties:
    cpu: 2
    disk: 10480
    ram: 4096
  name: services-small
  #size: 5
  network: op_dev_network
  stemcell:
    name: bosh-vsphere-esxi-ubuntu-trusty-go_agent
    version: "3012"
