name: openpaas-mysql-service
director_uuid: 0bc8d3c2-e032-4c7e-a99c-e23eea7091fc

releases:
- name: openpaas-mysql
  version: beta-1.0

update:
  canaries: 1
  canary_watch_time: 30000-600000
  max_in_flight: 1
  update_watch_time: 30000-600000

compilation:
  cloud_properties:
    cpu: 4
    disk: 20480
    ram: 4096
  network: openpass_network
  reuse_compilation_vms: true
  workers: 4

jobs:
- instances: 1
  name: mysql_z1
  networks:
  - name: openpass_network
    static_ips: 10.30.40.191
  persistent_disk: 10000
  properties:
    admin_password: admin
    cluster_ips:
    - 10.30.40.191
    - 10.30.40.192
    - 10.30.40.193
    network_name: openpass_network
    seeded_databases: null
    syslog_aggregator: null
    collation_server: utf8_unicode_ci
    character_set_server: utf8
  release: openpaas-mysql
  resource_pool: services-small
  template: mysql

- instances: 1
  name: mysql_z2
  networks:
  - name: openpass_network
    static_ips: 10.30.40.192
  persistent_disk: 10000
  properties:
    admin_password: admin
    cluster_ips:
    - 10.30.40.191
    - 10.30.40.192
    - 10.30.40.193
    network_name: openpass_network
    seeded_databases: null
    syslog_aggregator: null
    collation_server: utf8_unicode_ci
    character_set_server: utf8
  release: openpaas-mysql
  resource_pool: services-small
  template: mysql

- instances: 1
  name: mysql_z3
  networks:
  - name: openpass_network
    static_ips: 10.30.40.193
  persistent_disk: 10000
  properties:
    admin_password: admin
    cluster_ips:
    - 10.30.40.191
    - 10.30.40.192
    - 10.30.40.193
    network_name: openpass_network
    seeded_databases: null
    syslog_aggregator: null
    collation_server: utf8_unicode_ci
    character_set_server: utf8
  release: openpaas-mysql
  resource_pool: services-small
  template: mysql

- instances: 1
  name: proxy
  networks:
  - name: openpass_network
    static_ips: 10.30.40.194
  properties:
    cluster_ips:
    - 10.30.40.191
    - 10.30.40.192
    - 10.30.40.193
    external_host: cf.open-paas.com
    nats:
      machines:
      - 10.30.40.11
      password: admin
      port: 4222
      user: nats
    network_name: openpass_network
    proxy:
      api_password: admin
      api_username: api
      api_force_https: false
    syslog_aggregator: null
  release: openpaas-mysql
  resource_pool: services-small
  template: proxy

- instances: 1
  name: openpaas-mysql-java-broker
  networks:
  - name: openpass_network
    static_ips: 10.30.40.195
  properties:
    jdbc_ip: 10.30.40.194
    jdbc_pwd: admin
    jdbc_port: 3306
    log_dir: openpaas-mysql-java-broker
    log_file: openpaas-mysql-java-broker
    log_level: INFO
  release: openpaas-mysql
  resource_pool: services-small
  template: op-mysql-java-broker

- instances: 1
  lifecycle: errand
  name: broker-registrar
  networks:
  - name: openpass_network
  properties:
    broker:
      host: 10.30.40.195
      name: mysql-service
      password: cloudfoundry
      username: admin
      protocol: http
      port: 8080
    cf:
      admin_password: admin
      admin_username: admin
      api_url: http://api.controller.open-paas.com
      skip_ssl_validation: true
  release: openpaas-mysql
  resource_pool: services-small
  template: broker-registrar

- instances: 1
  lifecycle: errand
  name: broker-deregistrar
  networks:
  - name: openpass_network
  properties:
    broker:
      host: 10.30.40.195
      name: mysql-service
      password: cloudfoundry
      username: admin
      protocol: http
      port: 8080
    cf:
      admin_password: admin
      admin_username: admin
      api_url: http://api.controller.open-paas.com
      skip_ssl_validation: true
  release: openpaas-mysql
  resource_pool: services-small
  template: broker-deregistrar

meta:
  apps_domain: cf.open-paas.com
  environment: null
  external_domain: cf.open-paas.com
  nats:
    machines:
    - 10.30.40.11
    password: admin
    port: 4222
    user: nats
  syslog_aggregator: null

networks:
- name: openpass_network
  subnets:
  - cloud_properties:
      name: Internal
    dns:
    - 10.30.20.24
    - 8.8.8.8
    gateway: 10.30.20.23
    name: default_unused
    range: 10.30.0.0/16
    reserved:
    - 10.30.0.1 - 10.30.0.10
    static:
    - 10.30.40.110 - 10.30.40.200
  type: manual
properties: {}
resource_pools:
- cloud_properties:
    cpu: 2
    disk: 10480
    ram: 4096
  name: services-small
  network: openpass_network
  stemcell:
    name: bosh-vsphere-esxi-ubuntu-trusty-go_agent
    version: "3147"
