---
name: op-api-service

director_uuid: 6e0f7c41-2415-4319-98aa-38109597aff4

release:
  name: op-api-service-dev
  version: latest

networks:
- name: default
  subnets:
  - cloud_properties:
      name: Internal
    dns:
    - 10.30.20.24
    gateway: 10.30.20.23
    name: default_unused
    range: 10.30.0.0/16
    reserved:
    - 10.30.0.1 - 10.30.0.255
    - 10.30.40.1 - 10.30.40.70
    - 10.30.40.101 - 10.30.60.210
    - 10.30.60.221 - 10.30.255.254
    static:
    - 10.30.60.211 - 10.30.60.220
  type: manual

compilation:
  workers: 2
  network: default
  reuse_compilation_vms: true
  cloud_properties:
    ram: 2048
    disk: 8096
    cpu: 2

update:
  canaries: 1
  canary_watch_time: 30000-600000
  max_in_flight: 1
  update_watch_time: 30000-600000

resource_pools:
- name: api-service-resource_pool
  network: default
  stemcell:
    name: bosh-vsphere-esxi-ubuntu-trusty-go_agent
    version: 3012
  cloud_properties:
    cpu: 1
    disk: 8192
    ram: 2048

jobs:
- name: public-api-service-broker
  instances: 1
  template: public-api-service-broker
  resource_pool: api-service-resource_pool
  networks:
  - name: default
    static_ips: 10.30.60.213

- name: naver-api-service-broker
  instances: 1
  template: naver-api-service-broker
  resource_pool: api-service-resource_pool
  networks:
  - name: default
    static_ips: 10.30.60.218

- name: public-api-broker-registrar
  template: public-api-broker-registrar
  instances: 1
  lifecycle: errand
  resource_pool: api-service-resource_pool
  networks:
  - name: default
  properties:
    cf:
      api_url: http://api.cf.open-paas.com
      admin_username: "admin"
      admin_password: "eaa139af583c"
      skip_ssl_validation: "true"
    broker:
      protocol: http
      host: 10.30.60.213
      port: 8080
      name: public-api-service-broker
      username: "admin"
      password: "cloudfoundry"

- name: naver-api-broker-registrar
  template: naver-api-broker-registrar
  instances: 1
  lifecycle: errand
  resource_pool: api-service-resource_pool
  networks:
  - name: default
  properties:
    cf:
      api_url: http://api.cf.open-paas.com
      admin_username: "admin"
      admin_password: "eaa139af583c"
      skip_ssl_validation: "true"
    broker:
      protocol: http
      host: 10.30.60.218
      port: 8080
      name: naver-api-service-broker
      username: "admin"
      password: "cloudfoundry"
