---
packages:
- name: apimanager
  version: !binary |-
    Mjg3NmEwMzFkYjJhMjMzMzk4ZmFiYmEyNWQ2YzE0MjYyMGY3ZGY5NA==
  fingerprint: !binary |-
    Mjg3NmEwMzFkYjJhMjMzMzk4ZmFiYmEyNWQ2YzE0MjYyMGY3ZGY5NA==
  sha1: !binary |-
    N2FhMzU1MzU2YjNlOTg5YzYyYTBiYTMzNzgxMGNlNWFmZGU5OGVhMA==
  dependencies:
  - java7
- name: java7
  version: !binary |-
    NDgwODFkNzJiMDM4MjM4NTIxYmI1YjY1YTJmOWMyM2RiYzBkYzA0NQ==
  fingerprint: !binary |-
    NDgwODFkNzJiMDM4MjM4NTIxYmI1YjY1YTJmOWMyM2RiYzBkYzA0NQ==
  sha1: !binary |-
    N2JmN2YyMThkNTYwYjQzOWI1ZTIzZjM5NzM2Yzg4MmIxYjJmMmIxYg==
  dependencies: []
jobs:
- name: apimanager
  version: !binary |-
    OTg5N2ZiNzllNjM1MjJkOWMyMzcyOWZlMTkyNzhiMjA3ZDU2OTI3Mw==
  fingerprint: !binary |-
    OTg5N2ZiNzllNjM1MjJkOWMyMzcyOWZlMTkyNzhiMjA3ZDU2OTI3Mw==
  sha1: !binary |-
    MzMwZTljODdiZGQzMzFlZTg2MmU4Njg5NTI3Y2I4N2E4ZWM5YzUzZg==
commit_hash: '00000000'
uncommitted_changes: false
name: apiplatform_dev
version: 0+dev.3
