---
packages:
- name: mariadb
  version: !binary |-
    NzEyZDkzMWJiMTE1NDIzZTBkNjcyYjNjZjE1N2NkMzg2N2FiMTZiYQ==
  fingerprint: !binary |-
    NzEyZDkzMWJiMTE1NDIzZTBkNjcyYjNjZjE1N2NkMzg2N2FiMTZiYQ==
  sha1: !binary |-
    Nzk1ZjkwMjc5OTM5MTAwZWM1YTIzZWFkY2E3YTNiNWM2NThhNjhkZA==
  dependencies: []
- name: mysql_connector_java
  version: !binary |-
    MDYwMzNmZTEzMDhlYTczNTRhZjJkMjY4OTE3MWQ1M2M0MGQwMjhjNA==
  fingerprint: !binary |-
    MDYwMzNmZTEzMDhlYTczNTRhZjJkMjY4OTE3MWQ1M2M0MGQwMjhjNA==
  sha1: !binary |-
    ZDRjOGM4MDkwMTM1MGQ5NzA2MzQ0MmU3ZWEwZWRiMGIyOTE5YzY0NQ==
  dependencies: []
- name: bam
  version: !binary |-
    MzBkNmQwNDdjMWUyMjc5NTVhM2MzYWRlN2E0ZGYyZWZmNDk2NmNkOQ==
  fingerprint: !binary |-
    MzBkNmQwNDdjMWUyMjc5NTVhM2MzYWRlN2E0ZGYyZWZmNDk2NmNkOQ==
  sha1: !binary |-
    YmM4YTNhNjBkMDRhNjhjMTc2YmU4MDY4NjZlMDgyNWI1OWQ4NmVkZA==
  dependencies: []
- name: apimanager
  version: !binary |-
    ODA3MGY5ZWI4ZGE0YmNjNTI4ZWNhOTE3ZGYxYjViOTc0YTVjOTNkMw==
  fingerprint: !binary |-
    ODA3MGY5ZWI4ZGE0YmNjNTI4ZWNhOTE3ZGYxYjViOTc0YTVjOTNkMw==
  sha1: !binary |-
    ZWNjMjdhYzkwYjhmZmZkNDI0ZjZmYTJiNWQwYWI5NWM5OTFmYzIwZA==
  dependencies:
  - mysql_connector_java
- name: java7
  version: !binary |-
    NWUxZTdkNjc2OTkwMjk1YzA5NWI2MzJiZGRjNWM0MmMwZGExZmNjZA==
  fingerprint: !binary |-
    NWUxZTdkNjc2OTkwMjk1YzA5NWI2MzJiZGRjNWM0MmMwZGExZmNjZA==
  sha1: !binary |-
    OGE4NmM2Zjc2YzRjODAzNjNhNmE2YWE4MTIyMDJlMGU5YzJhMjlkYg==
  dependencies: []
jobs:
- name: apimanager
  version: !binary |-
    MmY1NWJhOGMzZDJmMzRjMGRiYTIyMTAyMTQzMGU3MmFmOTFjMDM4NQ==
  fingerprint: !binary |-
    MmY1NWJhOGMzZDJmMzRjMGRiYTIyMTAyMTQzMGU3MmFmOTFjMDM4NQ==
  sha1: !binary |-
    YWYxZTBjN2YzOTQ3OWVlODNmMmYzYTE2ZGFmNWI1MTRkNDlmODA2MA==
commit_hash: '00000000'
uncommitted_changes: false
name: apiplatform_dev
version: 0+dev.25
