---
packages:
- name: apimanager
  version: !binary |-
    MzZmNTI1N2FjYWMxNzAxZGU5NmFkZTczN2VmMzE5MTdmNjM2NDk4NQ==
  fingerprint: !binary |-
    MzZmNTI1N2FjYWMxNzAxZGU5NmFkZTczN2VmMzE5MTdmNjM2NDk4NQ==
  sha1: !binary |-
    N2EzYjQ1NzI1NGVmYjkzNGQ0NGJkMDY4MTIyZmFiYzRmYTUzY2NjMA==
  dependencies:
  - java7
- name: java7
  version: !binary |-
    OGM2ZGZiODA1MjJmMTdmZGJiYTNjMmRiYjc0ZjliNzc2MDliN2NmMw==
  fingerprint: !binary |-
    OGM2ZGZiODA1MjJmMTdmZGJiYTNjMmRiYjc0ZjliNzc2MDliN2NmMw==
  sha1: !binary |-
    MzQwZjg1ZDIxMmRiNmMwMWU3NjI5MjY5ZTkyMjhjM2IwYjk0ODNhMg==
  dependencies: []
jobs:
- name: apimanager
  version: !binary |-
    OTg5N2ZiNzllNjM1MjJkOWMyMzcyOWZlMTkyNzhiMjA3ZDU2OTI3Mw==
  fingerprint: !binary |-
    OTg5N2ZiNzllNjM1MjJkOWMyMzcyOWZlMTkyNzhiMjA3ZDU2OTI3Mw==
  sha1: !binary |-
    MzMwZTljODdiZGQzMzFlZTg2MmU4Njg5NTI3Y2I4N2E4ZWM5YzUzZg==
commit_hash: '00000000'
uncommitted_changes: false
name: apiplatform_dev
version: 0+dev.1
