---
packages:
- name: cubrid
  version: !binary |-
    MzYwNjViYjIyZDFlODE2NjU3ZDE3NmM5MDIyNDYyMzEzNDczNjFlMg==
  fingerprint: !binary |-
    MzYwNjViYjIyZDFlODE2NjU3ZDE3NmM5MDIyNDYyMzEzNDczNjFlMg==
  sha1: !binary |-
    N2IwZmE5NDZkMjlmMjkxOWY1Zjg3Y2QwOGFhMjZjNjFkZDQyNGQ2NA==
  dependencies: []
- name: cubrid_broker
  version: !binary |-
    ODA4NTQ1Y2I2MzE4MGI1MGUwYmMyYWEyYWQxMTg2YzQzNTBiYWRiNg==
  fingerprint: !binary |-
    ODA4NTQ1Y2I2MzE4MGI1MGUwYmMyYWEyYWQxMTg2YzQzNTBiYWRiNg==
  sha1: !binary |-
    NTcxOGMzNzlhNWY5YTkxMDkyOGJkNDJkODVhZjg5ZjkzODVkOTAwMQ==
  dependencies:
  - java7
- name: java7
  version: !binary |-
    Y2IyODUwMmY2ZTg5ODcwMjU1MTgyZWE3NmU5MDI5YzdlOWVjMTg2Mg==
  fingerprint: !binary |-
    Y2IyODUwMmY2ZTg5ODcwMjU1MTgyZWE3NmU5MDI5YzdlOWVjMTg2Mg==
  sha1: !binary |-
    MTQyMmU1MDllMzBkNTE3Y2NmODgxODYxMzA1ODk3MWZhMjA1MzI3MQ==
  dependencies: []
jobs:
- name: cubrid
  version: !binary |-
    NDU0MjdjYjVmM2I2Yzg2ZGY4MGJiMmRlMzhjMTJlOThhZWM3Yjk1Zg==
  fingerprint: !binary |-
    NDU0MjdjYjVmM2I2Yzg2ZGY4MGJiMmRlMzhjMTJlOThhZWM3Yjk1Zg==
  sha1: !binary |-
    YWE1MjdmZTcxMzZhMDI1YjYxNDRiNzExMmVjYTc5NWYzOThhOTdhMg==
- name: cubrid_broker
  version: !binary |-
    YWFhZGY1OTY1YjNlYjgyZTFmZjFmNjc5YmM2OGNmNzZmYjU2MzRkZQ==
  fingerprint: !binary |-
    YWFhZGY1OTY1YjNlYjgyZTFmZjFmNjc5YmM2OGNmNzZmYjU2MzRkZQ==
  sha1: !binary |-
    YTM2MzdhNDUyMmM4ZTlmNjU2NzFmMmU1ZjZkOThiM2JjMWRjZjhiMg==
commit_hash: '00000000'
uncommitted_changes: false
name: cubrid_dev
version: 0+dev.47
