# paasta-cubrid-aws 설정 파일 내용
---
name: paasta-cubrid-service                         # 서비스 배포이름(필수)
director_uuid: d363905f-eaa0-4539-a461-8c1318498a32 #bosh status 에서 확인한 Director UUID을 입력(필수)

releases:
- name: paasta-cubrid                               #서비스 릴리즈 이름(필수)
  version: 2.0                                      #서비스 릴리즈 버전(필수):latest 시 업로드된 서비스 릴리즈 최신버전

compilation:                                        # 컴파일시 필요한 가상머신의 속성(필수)
  workers: 2                                        # 컴파일 하는 가상머신의 최대수(필수)
  network: default                                  # Networks block에서 선언한 network 이름(필수)
  reuse_compilation_vms: true
  cloud_properties:                                 # 컴파일 VM을 만드는 데 필요한 IaaS의 특정 속성 (instance_type, availability_zone)
    availability_zone: ap-northeast-2a
    instance_type: c4.large

# this section describes how updates are handled
update:
  canaries: 1                                        # canary 인스턴스 수(필수)
  canary_watch_time: 120000                          # canary 인스턴스가 수행하기 위한 대기 시간(필수)
  update_watch_time: 120000                          # 컴파일 시 필요한 가상머신의 속성(필수)
  max_in_flight: 4                                   # non-canary 인스턴스가 병렬로 update 하는 최대 개수(필수)

# 네트워크 블록에 나열된 각 서브 블록이 참조 할 수있는 작업이 네트워크 구성을 지정, 네트워크 구성은 네트워크 담당자에게 문의 하여 작성 요망
networks:
- name: default
  type: manual
  subnets:
  - range: 10.0.0.0/24
    gateway: 10.0.0.1
    dns: [10.0.0.6, 8.8.8.8]                         # DNS 정보
    reserved: ["10.0.0.2 - 10.0.0.69"]               # 설치시 제외할 IP 설정
    static: ["10.0.0.70 - 10.0.0.100"]
    cloud_properties:
      subnet: subnet-cdfc80a4                        # AWS subnet id
      security_groups:
        - psta-cf-security
        - psta-bosh-security
- name: public_network
  type: vip
  cloud_properties: {}

resource_pools:                                       # 배포시 사용하는 resource pools를 명시하며 여러 개의 resource pools 을 사용할 경우 name 은 unique 해야함(필수)
  - name: resource_pools                              # 고유한 resource pool 이름
    network: default
    stemcell:
      name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent   # stemcell 이름(필수)
      version: 3263.8                                 # stemcell 버전(필수)
    cloud_properties:                                 # 컴파일 VM을 만드는 데 필요한 IaaS의 특정 속성을 설명 (instance_type, availability_zone), 직접 cpu, disk, 메모리 설정가능
      cpu: 1
      disk: 8192
      ram: 2048

jobs:
  - name: cubrid                                      #작업 이름(필수): Cubrid 서버
    template: cubrid                                  # job template 이름(필수)
    instances: 1                                      # job 인스턴스 수(필수)
    resource_pool: cubrid_resource_pools              # resource_pools block에 정의한 resource pool 이름(필수)
#    persistent_disk: 16384  # 영구적 디스크 사이즈 정의(옵션): 16G
    networks:                                         # 네트워크 구성정보
    - name: default                                   # Networks block에서 선언한 network 이름(필수)
      static_ips:
      - 10.30.60.23                                   # 사용할 IP addresses 정의(필수): MySQL 서버 IP
  - name: cubrid_broker                               #작업 이름(필수): Cubrid 서비스 브로커
    template: cubrid_broker                           # job template 이름(필수)
    instances: 1                                      # job 인스턴스 수(필수)
    resource_pool: cubrid_resource_pools              # resource_pools block에 정의한 resource pool 이름(필수)
    networks:                                         # 네트워크 구성정보
    - name: default                                   # Networks block에서 선언한 network 이름(필수)
      static_ips:
      - 10.30.60.22                                   # 사용할 IP addresses 정의(필수)

  - name : cubrid_broker_registrar                    # 작업 이름: 서비스 브로커 등록
    template : cubrid_broker_registrar                # job template 이름(필수)
    instances: 1                                      # job 인스턴스 수(필수)
    lifecycle: errand                                 # bosh deploy시 vm에 생성되어 설치 되지 않고 bosh errand 로 실행할때 설정, 주로 테스트 용도에 쓰임
    resource_pool: cubrid_resource_pools              # Resource Pools block에 정의한 resource pool 이름(필수)
    networks:                                         # 네트워크 구성정보
    - name: default                                   # Networks block에서 선언한 network 이름(필수)
    properties:
      broker:                                         # 서비스 브로커 설정 정보
        host: 10.30.60.22                             # 서비스 브로커 IP 
        name: CubridDB                                # CF에서 서비스 브로커를 생성시 생기는 서비스 이름 브로커에 고정되어있는 값
        password: cloudfoundry                        # 브로커 접근 아이디 비밀번호(필수)
        username: admin                               # 브로커 접근 아이디(필수)
        protocol: http
        port: 8088                                    # 브로커 포트
      cf:
        admin_password: admin                         # CF 사용자의 패스워드
        admin_username: admin                         # CF 사용자 이름
        api_url: https://api.115.68.46.30.xip.io      # CF 설치시 설정한 api uri 정보(필수)
    release: paasta-cubrid
  - name : cubrid_broker_deregistrar                  #작업 이름: 서비스 브로커 삭제
    template : cubrid_broker_deregistrar              # job template 이름(필수) 
    instances: 1                                      # job 인스턴스 수(필수)
    lifecycle: errand                                 # bosh deploy시 vm에 생성되어 설치 되지 않고 bosh errand 로 실행할 때 설정, 주로 테스트 용도에 쓰임
    resource_pool: cubrid_resource_pools              # Resource Pools block에 정의한 resource pool 이름(필수)
      networks:                                       # 네트워크 구성정보
      - name: default                                 # Networks block에서 선언한 network 이름
    properties:
      broker:
        host: 10.30.60.22                             # API Platform Service Broker 접속 URL
        name: CubridDB                                # API Platform Service Broker 생성명
        username: admin                               # API Platform Service Broker auth 유저이름
        password: cloudfoundry                        # API Platform Service Broker auth 패스워드
        protocol: http                                # API Platform Service Broker 접속 프로토콜
        port: 8088                                    # API Platform Service Broker 접속 포트
      cf:
        admin_username: admin                         # PaaS-TA 접속 유저이름
        admin_password: admin                         # PaaS-TA 접속 패스워드
        api_url: https://api.115.68.46.30.xip.io      # PaaS-TA 접속 URL
    release: paasta-cubrid

meta:
  apps_domain: 115.68.46.30.xip.io                    # PaaS-TA 설치시 설정한 apps 도메인 정보
  environment: null
  external_domain: 115.68.46.30.xip.io                # PaaS-TA 설치시 설정한 외부 도메인 정보
  nats:                                               # CF 설치시 설정한 nats 정보
    machines:
    - 10.30.110.31
    password: nats
    port: 4222
    user: nats
  syslog_aggregator: null


properties:
  cubrid:                                             # Cubrid 설정 정보
    max_clients: 200
  cubrid_broker:                                      # Cubrid Servcice Broker 설정 정보
    cubrid_ip: 10.30.60.23                            # Cubrid IP
    cubrid_db_port: 30000                             # Cubrid Port
    cubrid_db_name: cubrid_broker                     # Cubrid service 관리를 위한 데이터베이스 이름
    cubrid_db_user: dba                               # 브로커 관리용 데이터베이스 접근 사용자이름
    cubrid_db_passwd: openpaas                        # 브로커 관리용 데이터베이스 접근 사용자 비밀번호
    cubrid_ssh_port: 22                               # Cubrid가 설치된 서버 SSH 접속 포트
    cubrid_ssh_user: vcap                             # Cubrid가 설치된 서버 SSH 접속 사용자 이름
    cubrid_ssh_passwd: c1oudc0w                       # Cubrid가 설치된 서버 SSH 접속 사용자 비밀번호
     cubrid_ssh_sudo_passwd: c1oudc0w                 # Cubrid가 설치된 서버 sudo 비밀번호
