---
packages:
- name: mongodb_broker
  version: !binary |-
    YjljZTVhZTFiYTUzZjk0NTEyZWJhNGM0ODczMzQxNDU2NjRiMjg3Mg==
  fingerprint: !binary |-
    YjljZTVhZTFiYTUzZjk0NTEyZWJhNGM0ODczMzQxNDU2NjRiMjg3Mg==
  sha1: !binary |-
    NzNkYmEwZjg3ODJhYTZlMDY1NDM2MmQ4YTlhMjAzZDk5NjY1NGMwMw==
  dependencies:
  - java7
- name: mongodb
  version: !binary |-
    YjM1NWFjMDQ1YjI1N2U2YTBjZWM4NTg3NGM2ZmI2ZTdhYmU5MmI2ZA==
  fingerprint: !binary |-
    YjM1NWFjMDQ1YjI1N2U2YTBjZWM4NTg3NGM2ZmI2ZTdhYmU5MmI2ZA==
  sha1: !binary |-
    NGU3NWQxZDNiZDY1MzE0NGM2ZTAwMWY1ZGM5OGRjNDFiYzgyMTk1OA==
  dependencies: []
- name: cli
  version: !binary |-
    MjQzMDVlNTBhNjM4ZWNlMmNhY2U0ZWY0ODAzNzQ2YzBjOWZlNGJiMA==
  fingerprint: !binary |-
    MjQzMDVlNTBhNjM4ZWNlMmNhY2U0ZWY0ODAzNzQ2YzBjOWZlNGJiMA==
  sha1: !binary |-
    ODdmZWRjZDFkZDRjOTBmMzI3ODhiM2M2OTM4NjIyODUyY2Q4NTFkMg==
  dependencies: []
- name: java7
  version: !binary |-
    Y2IyODUwMmY2ZTg5ODcwMjU1MTgyZWE3NmU5MDI5YzdlOWVjMTg2Mg==
  fingerprint: !binary |-
    Y2IyODUwMmY2ZTg5ODcwMjU1MTgyZWE3NmU5MDI5YzdlOWVjMTg2Mg==
  sha1: !binary |-
    MjE4ODIxNGZmMDdhNWFiNTVlZjE0NjdiY2ZhZGUzMzMyOGZhOWMxMw==
  dependencies: []
jobs:
- name: mongodb_broker
  version: !binary |-
    MTBkYTJmM2MwZTM3NGIwMWY4MThiMjhmZjVlY2I4MDQ0ZmQwY2QxYQ==
  fingerprint: !binary |-
    MTBkYTJmM2MwZTM3NGIwMWY4MThiMjhmZjVlY2I4MDQ0ZmQwY2QxYQ==
  sha1: !binary |-
    MTY2MzY4NjhjN2YzYzg2Y2IxMGFiZWM4MTQ4NTM4NTM2MWZjZmZlOQ==
- name: mongodb_config
  version: !binary |-
    ZGNiOWM3MDdkNGU5NzU3YTE1MGY1NDBlZTVhZjM5ZWZiODU4MGYwNA==
  fingerprint: !binary |-
    ZGNiOWM3MDdkNGU5NzU3YTE1MGY1NDBlZTVhZjM5ZWZiODU4MGYwNA==
  sha1: !binary |-
    OGJjNDVkZjUyNzQ2ZTcxMzIxMDEwZjM5YzBiYjE3NjQzNTc4MzRlZg==
- name: mongodb_shard
  version: !binary |-
    OGM5MTVlMTA3ZGE1ZmZlMTc5ZDhmMzAzZTUyNzVkOWY3OGM2ZmUwOA==
  fingerprint: !binary |-
    OGM5MTVlMTA3ZGE1ZmZlMTc5ZDhmMzAzZTUyNzVkOWY3OGM2ZmUwOA==
  sha1: !binary |-
    ZjBhZTA0Y2IwZGE3NGFiMDdmZDg5YjFjMjg4M2VlNTZkNDAyOWYyOA==
- name: mongodb_master
  version: !binary |-
    YWRmYzE5OWM5ZDJmM2FjZWFmMzFmZTU2ZTU1M2UxNWZhZjYwNWVlNw==
  fingerprint: !binary |-
    YWRmYzE5OWM5ZDJmM2FjZWFmMzFmZTU2ZTU1M2UxNWZhZjYwNWVlNw==
  sha1: !binary |-
    MTI2YjAzNTA5ODgyZWE3OGZiMTc1ZWE0Y2QyOTI4YTc3MmQ5NzNjNg==
- name: mongodb_slave
  version: !binary |-
    Y2QxOGM1MTg3ZjQ0ZjhlM2QxZDJjNzkzNzA0N2NjNzQ4YTg1MWE0Mw==
  fingerprint: !binary |-
    Y2QxOGM1MTg3ZjQ0ZjhlM2QxZDJjNzkzNzA0N2NjNzQ4YTg1MWE0Mw==
  sha1: !binary |-
    NWNiZjVlY2U2YzgwYTRjZjY3ZTg1NmQyOGIwNjc3MGIzYmNlYzA4Zg==
- name: mongodb_broker_registrar
  version: !binary |-
    YTQ4OTJhN2RmZWM3YWNkYzdiYTBjZDI2MThhNzllZTNiMmY4MGQ5Yg==
  fingerprint: !binary |-
    YTQ4OTJhN2RmZWM3YWNkYzdiYTBjZDI2MThhNzllZTNiMmY4MGQ5Yg==
  sha1: !binary |-
    ZjJkNGU1OGI2Yzg1MTJmMDkyMzUwODI4ZjEyYzY3MzVjZjY2MTJlNA==
- name: mongodb_broker_deregistrar
  version: !binary |-
    ZDc5N2YwNjhlODkyNjUzMTM0MzZiN2M2NDM5ZDkzMjg4ZDBmYWZiZQ==
  fingerprint: !binary |-
    ZDc5N2YwNjhlODkyNjUzMTM0MzZiN2M2NDM5ZDkzMjg4ZDBmYWZiZQ==
  sha1: !binary |-
    YTVkYzQyYzdiNjU1ZGUzYTEyM2E5NDVjYjE3OWUxZDg3YzFkZDEzYg==
commit_hash: bbb5d475
uncommitted_changes: true
name: op-mongodb-shard-dev
version: 0+dev.9
