---
packages:
- name: mongodb_broker
  version: !binary |-
    YjljZTVhZTFiYTUzZjk0NTEyZWJhNGM0ODczMzQxNDU2NjRiMjg3Mg==
  fingerprint: !binary |-
    YjljZTVhZTFiYTUzZjk0NTEyZWJhNGM0ODczMzQxNDU2NjRiMjg3Mg==
  sha1: !binary |-
    NzNkYmEwZjg3ODJhYTZlMDY1NDM2MmQ4YTlhMjAzZDk5NjY1NGMwMw==
  dependencies:
  - java7
- name: mongodb
  version: !binary |-
    YjM1NWFjMDQ1YjI1N2U2YTBjZWM4NTg3NGM2ZmI2ZTdhYmU5MmI2ZA==
  fingerprint: !binary |-
    YjM1NWFjMDQ1YjI1N2U2YTBjZWM4NTg3NGM2ZmI2ZTdhYmU5MmI2ZA==
  sha1: !binary |-
    NGU3NWQxZDNiZDY1MzE0NGM2ZTAwMWY1ZGM5OGRjNDFiYzgyMTk1OA==
  dependencies: []
- name: cli
  version: !binary |-
    MjQzMDVlNTBhNjM4ZWNlMmNhY2U0ZWY0ODAzNzQ2YzBjOWZlNGJiMA==
  fingerprint: !binary |-
    MjQzMDVlNTBhNjM4ZWNlMmNhY2U0ZWY0ODAzNzQ2YzBjOWZlNGJiMA==
  sha1: !binary |-
    ODdmZWRjZDFkZDRjOTBmMzI3ODhiM2M2OTM4NjIyODUyY2Q4NTFkMg==
  dependencies: []
- name: java7
  version: !binary |-
    Y2IyODUwMmY2ZTg5ODcwMjU1MTgyZWE3NmU5MDI5YzdlOWVjMTg2Mg==
  fingerprint: !binary |-
    Y2IyODUwMmY2ZTg5ODcwMjU1MTgyZWE3NmU5MDI5YzdlOWVjMTg2Mg==
  sha1: !binary |-
    MjE4ODIxNGZmMDdhNWFiNTVlZjE0NjdiY2ZhZGUzMzMyOGZhOWMxMw==
  dependencies: []
jobs:
- name: mongodb_broker
  version: !binary |-
    MTBkYTJmM2MwZTM3NGIwMWY4MThiMjhmZjVlY2I4MDQ0ZmQwY2QxYQ==
  fingerprint: !binary |-
    MTBkYTJmM2MwZTM3NGIwMWY4MThiMjhmZjVlY2I4MDQ0ZmQwY2QxYQ==
  sha1: !binary |-
    MTY2MzY4NjhjN2YzYzg2Y2IxMGFiZWM4MTQ4NTM4NTM2MWZjZmZlOQ==
- name: mongodb_config
  version: !binary |-
    MmZlYWZjYTViYjRkOGVhYTRiN2QzODI4MDMwYThhYzkxMjQ1OWYyYw==
  fingerprint: !binary |-
    MmZlYWZjYTViYjRkOGVhYTRiN2QzODI4MDMwYThhYzkxMjQ1OWYyYw==
  sha1: !binary |-
    MjQ2ODZlYjQzZDU5YjdiMzg1OGM2ZWZiNjUzYTJjYzdiYjY3ZGQ4Yg==
- name: mongodb_shard
  version: !binary |-
    ZjU1MDJiMzQ2ZTNiNjg4NmJjMDFjMjQwYjMzZDU2OTBiMDZkOWM4NQ==
  fingerprint: !binary |-
    ZjU1MDJiMzQ2ZTNiNjg4NmJjMDFjMjQwYjMzZDU2OTBiMDZkOWM4NQ==
  sha1: !binary |-
    Nzc3OGFkZTY0ODk0ZDkwMzdlZTkxMTY1NWJkNWU4ZTU5ZDA5MDk2Yw==
- name: mongodb_master
  version: !binary |-
    OTFkODU4Yzk3OTM4YjhjZTY4ZjAxMWI0NWM1ZTQxNTlhNjMwOGU5MA==
  fingerprint: !binary |-
    OTFkODU4Yzk3OTM4YjhjZTY4ZjAxMWI0NWM1ZTQxNTlhNjMwOGU5MA==
  sha1: !binary |-
    NTg4NTYyZTQwMjJhMGRlZjY3OGQ0NmIyZGY3ODNkZDgwN2M0ZTJlNw==
- name: mongodb_slave
  version: !binary |-
    YmI4NTY1ZjY4Njc5ODQ3ODQ5MjZmNTkzOTRjOWM1NWI1Zjg5ZDM0ZA==
  fingerprint: !binary |-
    YmI4NTY1ZjY4Njc5ODQ3ODQ5MjZmNTkzOTRjOWM1NWI1Zjg5ZDM0ZA==
  sha1: !binary |-
    NjYzNmY3MGJlOWQyNGIxZjFhZGIzMTMyYzg0NzA2ZjgxNzJhMGE1ZQ==
- name: mongodb_broker_registrar
  version: !binary |-
    YTQ4OTJhN2RmZWM3YWNkYzdiYTBjZDI2MThhNzllZTNiMmY4MGQ5Yg==
  fingerprint: !binary |-
    YTQ4OTJhN2RmZWM3YWNkYzdiYTBjZDI2MThhNzllZTNiMmY4MGQ5Yg==
  sha1: !binary |-
    ZjJkNGU1OGI2Yzg1MTJmMDkyMzUwODI4ZjEyYzY3MzVjZjY2MTJlNA==
- name: mongodb_broker_deregistrar
  version: !binary |-
    ZDc5N2YwNjhlODkyNjUzMTM0MzZiN2M2NDM5ZDkzMjg4ZDBmYWZiZQ==
  fingerprint: !binary |-
    ZDc5N2YwNjhlODkyNjUzMTM0MzZiN2M2NDM5ZDkzMjg4ZDBmYWZiZQ==
  sha1: !binary |-
    YTVkYzQyYzdiNjU1ZGUzYTEyM2E5NDVjYjE3OWUxZDg3YzFkZDEzYg==
commit_hash: bbb5d475
uncommitted_changes: true
name: op-mongodb-shard-dev
version: 0+dev.5
